### ISSUE TITLE
Months missing 0

### ISSUE THREAD

**Issue by Dtrieb** [lochidev/Expandroid#27]
If I add a date per template it miss a zero.

P.e.:

Today: 10.8.2024
But I want 10.**0**8.2024

**Comment by lochidev** [comment]
Hi! What is your app version?
By template do you mean the in app template buttons?

I've tested in the in app templates and https://github.com/lochidev/TextToolsPro/blob/main/examples/config.yml and in both instances I get "10/08/2024". If you can share your config we could find out the error.

**Comment by Dtrieb** [comment]
Ah!

I found my error, my variable {mydate} was set to:
format: dd.M.yyyy there I miss a **M** 
I've had to write format: dd.MM.yyyy

Sorry!

**Comment by Dtrieb** [comment]
One question:

Why add
format: ddHHmmMMMyy

A dot :drkdatum

**Comment by lochidev** [comment]
That is also weird. No dot in my end.

**Comment by lochidev** [comment]
You can also mess around by changing the string in this ToString() method here: https://dotnetfiddle.net/yA5DFt 

That is what is happening under the hood in this app.

Docs: https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings

**Comment by Dtrieb** [comment]
```
- trigger: :drkdatum
  replace: '{{mydate}}'
  vars:
  - name: mydate
    type: date
    params:
      echo: 
      format: ddHHmmMMMyy
      offset: 0
      cmd: 
      choices: 
  word: false
```

That's what I use.
