### ISSUE TITLE
triggering doesnt work in most apps, and when it does curses jumps around and makes a mess.

### ISSUE THREAD

**Issue by rifling-pixel** [lochidev/Expandroid#50]
Hi there, i'm using Expandroid without any real issues since a long time, but recently, I'm not able to anything with it anymore (besides using it in chat apps)

Mostly, I ~~could really~~ absolutely need it for Notesnook. idk, how to explain, but stuff gets not triggered, then triggered and tossed arround, emply lines are deleted, site scrolls up and dows, layout is a mess. Sorry, not, really detailed, tried to upload a Video, but its too big. 
Hope anyone can tell me what went wrong.

**Comment by lochidev** [comment]
More information would be useful.
1. Did you make android OS upgrade lately?
2. Did these issue come about after updating the app? If so version numbers would help.

Some things you can try. First, backup/export the config first and maybe post it here too.
1. Turn off the accessibility service and turn it on again. This will reset some things.
2. Try uninstalling and reinstalling the app.
3. Try an older version of the app in the github releases section.

**Comment by rifling-pixel** [comment]
Thanks for your reply. The problem persists no matter what; but never the same way.

Sometimes everything works as expected, sometimes things dont get  triggered or only after the second or third time, sometimes only after an additional press of space or enter, sometimes parts of value are doubled, sometimes after being triggered the cursor jumps to the very beginning of the text field (can be avoided with $|$), sometimes (all) previous empty lines are deleted after something gets triggered. 

No idea, but because its so inconsistent and weird, its probably my phone, no idea. Anyway, thanks for all your work and the great app! All the best!

**Comment by lochidev** [comment]
what is the version of the app you are using? 
android OS version?
if possible please provide your config so I can debug easily. Unfortunately my semester has already started and I'm very busy these days, so might take a while to get this sorted out.

**Comment by rifling-pixel** [comment]
I tried with different android OS; always the same issue, so I had to switch to another app. Hope you will find more time in the future to develop again, cuz its a gem! All other similar apps have all kinds of trackers and permissions like full network access and whatnot, yuck. I honestly think you could make a decent living from that app. Anyway, wish you all the best, and again: "amazing app, thanks for making it ❤️"  😉

**Comment by lochidev** [comment]
Hi. Any chance you can share your config? Sometimes that is the issue. There maybe errors when parsing the config.

**Comment by kranix0** [comment]
I'm seeing this too. The cursor can jump to the top after resolving the rule. 

My config:

```yaml
global_vars: []
matches:
- trigger: :d
  replace: '{{dateiso}}'
  vars:
  - name: dateiso
    type: date
    params:
      echo: ''
      format: '%Y-%m-%%e'
      offset: 0
      cmd: 
      layout: 
      choices: 
  form: 
  form_fields: 
  word: false
- trigger: --
  replace: –
  vars: []
  form: 
  form_fields: 
  word: false

```
